<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button1</name>
   <tag></tag>
   <elementGuidId>531ed1c3-e441-40c3-99b4-903067284c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Button1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Button1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1acf9a3-41e8-4640-bc5c-4e2f4c113c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0c5af67d-4546-4531-8b3a-83c45a606636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Button1</value>
      <webElementGuid>c8fe367b-8056-4036-9594-6c905c60e14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>3c9763f3-6ff6-467c-b879-68013da4f260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Button1</value>
      <webElementGuid>0c7e3ca9-879c-4811-b4f0-e24d53785ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>b9431fd4-d633-42dc-8a86-4b4e5894c7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Button1&quot;)</value>
      <webElementGuid>eb03797d-2eae-48e3-a3c3-7680140d72ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Button1']</value>
      <webElementGuid>7166a0ae-3c11-4d09-9f19-345992fc3a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginContainer']/form/div[4]/div/input</value>
      <webElementGuid>5c3d631c-a15a-4669-a398-897ecc237193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>cdbb59bb-9fee-4aee-9d22-918da11f9c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'Button1' and @id = 'Button1']</value>
      <webElementGuid>e256078a-34a6-437f-8b23-773e6f9b8035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
