<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeIn</name>
   <tag></tag>
   <elementGuidId>6dcd38a3-811a-40fe-9111-c223af8400ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logTimeIn1EditingInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logTimeIn1EditingInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a9bbbce-1ac3-4c40-8d8a-ec83f2201bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6cea5e9-c06f-4c44-ba7e-a8bbd6421a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>1dd0e64d-b33d-4e31-a30c-2722352093fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeIn1EditingInput</value>
      <webElementGuid>7df88dde-f461-45e0-a019-e5f802dba073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>046f8e2d-4d91-40cb-84ba-415a1e29acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>cb218f53-fdfa-4658-8072-0f992f756104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeIn1EditingInput&quot;)</value>
      <webElementGuid>6a8ee3e0-ca01-4c97-9e80-bd5810cf1cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logTimeIn1EditingInput']</value>
      <webElementGuid>74107d65-bda0-4ace-b61f-f43e7afa3542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTimeIn1']/div[3]/input</value>
      <webElementGuid>2cc19e63-85c3-4fd6-aaaf-90ab1bbce9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>e5698a68-10bc-484c-894b-9e4df5b0350c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'logTimeIn1EditingInput']</value>
      <webElementGuid>1937472e-47c1-4cd2-a9fb-2264fa57c75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
