<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeOut</name>
   <tag></tag>
   <elementGuidId>96d76dea-b209-4545-80b9-7390fa9996a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logTimeOut1EditingInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logTimeOut1EditingInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>115f63db-acd8-4fcb-8859-6cf89cf55eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>213b3999-24e1-4e3b-a23e-3734417b3e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>3cbd0c71-835c-4fab-9dcb-7c7c60e0085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeOut1EditingInput</value>
      <webElementGuid>f764b8b9-d847-4ae7-9362-6c9e2ab1eba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>87f29f3a-6796-43a6-ba75-78706bc9e5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>910f0b61-d854-4623-a258-15051e1c8908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeOut1EditingInput&quot;)</value>
      <webElementGuid>314041d5-6a3f-4617-82cf-ec0a710eb449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ceb4200f-751e-4edb-a475-25c56bff7896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3dd15e4-c1b8-402e-8d34-aa237cecc619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>3b60a71b-e32d-44c2-af25-7fefe6241fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeOut1EditingInput</value>
      <webElementGuid>7251c31b-43c8-4aaf-8a8c-f357576648b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ebd5370a-8048-49ca-ab3b-3b38de924122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>bd983c20-a3be-4b5e-b11f-7a3aa568ad97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeOut1EditingInput&quot;)</value>
      <webElementGuid>f66a532d-e28f-4d3c-9d9d-e5ebba09923f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logTimeOut1EditingInput']</value>
      <webElementGuid>7b4b552e-5b5f-4633-8ea0-e9a87339f51e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTimeOut1']/div[3]/input</value>
      <webElementGuid>b186c0d9-7f03-45c4-b0b4-23ac1d7019ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/input</value>
      <webElementGuid>a9e57320-2df7-4c74-900a-760c43eee274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'logTimeOut1EditingInput']</value>
      <webElementGuid>e427b82a-0737-42b1-b5b4-37f3b060590c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
