<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My Attendance_SearchText</name>
   <tag></tag>
   <elementGuidId>154eb6e3-579a-45e3-bb5c-2f56b2d51853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b47ce9ed-8b5e-4b31-88ba-a6dd6b825473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-igedit-input ui-igvalidator-target ui-igedit-placeholder</value>
      <webElementGuid>2143098b-bcfc-4305-a75f-0701becc72c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchText</value>
      <webElementGuid>dfb94c96-c0cb-4039-a849-ab406911cbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9191b126-7391-4d14-b612-cfe40d0134b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>bc595842-f070-4b28-a9fa-cf781203f5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c940499c-c094-4b2f-8ea6-6ec502f1730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Text Editor</value>
      <webElementGuid>1ad69a21-1ee0-4e16-8c2f-2b4dc37eb031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchText&quot;)</value>
      <webElementGuid>ad9941f5-dd1b-4b9e-9fb1-b929e848870e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchText']</value>
      <webElementGuid>19488a4b-d88e-4ca7-95d2-4af0c4cd4ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterContent']/div/div/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>574e091a-0d5a-436d-9452-e5ec073bb13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a4c4f837-3309-4af1-8874-5a47740f6edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchText' and @type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>7fb0f695-49b9-42b8-9503-d267bb05819a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
